[package]
name = "cast-gtts"
version = "0.1.0"
authors = ["Masakuni Ito"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
rust_cast = "*"
gtts = { git = "https://github.com/masakuni-ito/gtts" }
